### PR TITLE
make subject in config optional

### LINKED ISSUE #1: Make 'subjects' field optional
At the moment, **subjects** is a mandatory field. It'd be useful to make it optional so developers can listen to all the incoming emails, not the ones with specific subjects.

### PR DESCRIPTION
**Pull request by johnrackles**
fixes #1

### CODE REVIEW

**Comment by domcorvasce** [comment]
That's great!
I'm very sorry to bother you, but it would amazing if you could follow the [Standard JS style-guide](https://standardjs.com/). You can lint your code with `npm run lint` to check everything is ok.

**Comment by johnrackles** [comment]
Hi, I fixed the formatting :)

**Comment by domcorvasce** [comment]
Looks very neat :party:! As last step before the merge, can you rebase it so we can have the last feature implemented by https://github.com/domcorvasce/rtteo/pull/4.

**Comment by domcorvasce** [comment]
That's great! Thank you for your contribution :+1:

**Pull request merged**
